import type { Transaction } from '@/types';

export const DEMO_TRANSACTIONS: Transaction[] = [
  {
    id: 'demo-1',
    user_id: null,
    line_user_id: null,
    line_message_id: null,
    image_hash: null,
    status: 'confirmed',
    transaction_type: 'bill_payment',
    payment_status: 'success',
    amount: 110.00,
    currency: 'THB',
    date_display: '23 ก.พ. 2569',
    time_display: '19:18',
    transaction_datetime_iso: '2026-02-23T19:18:00+07:00',
    payer_name: 'นายแมน ธ***',
    receiver_name: null,
    merchant_name: 'ซุปเปอร์เล้งข้าวหอม',
    bank_name: 'Krungthai',
    reference_no: 'C2026022360541958220',
    merchant_code: 'KB000002064298',
    transaction_code: 'KPS004KB000002064298',
    fee: 0,
    category_guess: 'food',
    category_final: 'food',
    confidence_score: 0.88,
    raw_ocr_text: 'สลิปการโอนเงิน...',
    raw_provider_response: null,
    parsed_result: null,
    source_image_url: null,
    drive_file_url: null,
    sheets_sync_status: 'synced',
    drive_sync_status: 'synced',
    notes: null,
    source: 'line',
    created_at: '2026-02-23T12:18:00Z',
    updated_at: '2026-02-23T12:20:00Z',
  },
  {
    id: 'demo-2',
    user_id: null,
    line_user_id: null,
    line_message_id: null,
    image_hash: null,
    status: 'confirmed',
    transaction_type: 'merchant_payment',
    payment_status: 'success',
    amount: 459.00,
    currency: 'THB',
    date_display: '24 ก.พ. 2569',
    time_display: '12:35',
    transaction_datetime_iso: '2026-02-24T12:35:00+07:00',
    payer_name: 'นายแมน ธ***',
    receiver_name: null,
    merchant_name: 'Tops Supermarket',
    bank_name: 'SCB',
    reference_no: 'SCB20260224123500001',
    merchant_code: null,
    transaction_code: null,
    fee: 0,
    category_guess: 'shopping',
    category_final: 'shopping',
    confidence_score: 0.92,
    raw_ocr_text: '',
    raw_provider_response: null,
    parsed_result: null,
    source_image_url: null,
    drive_file_url: null,
    sheets_sync_status: 'synced',
    drive_sync_status: 'pending',
    notes: null,
    source: 'line',
    created_at: '2026-02-24T05:35:00Z',
    updated_at: '2026-02-24T05:36:00Z',
  },
  {
    id: 'demo-3',
    user_id: null,
    line_user_id: null,
    line_message_id: null,
    image_hash: null,
    status: 'pending_confirmation',
    transaction_type: 'transfer',
    payment_status: 'success',
    amount: 1500.00,
    currency: 'THB',
    date_display: '25 มี.ค. 2569',
    time_display: '08:45',
    transaction_datetime_iso: '2026-03-25T08:45:00+07:00',
    payer_name: 'นายแมน ธ***',
    receiver_name: 'น.ส.สมหญิง ใ***',
    merchant_name: null,
    bank_name: 'Bangkok Bank',
    reference_no: 'BBL202603250845001',
    merchant_code: null,
    transaction_code: null,
    fee: 0,
    category_guess: 'transfer',
    category_final: null,
    confidence_score: 0.75,
    raw_ocr_text: '',
    raw_provider_response: null,
    parsed_result: null,
    source_image_url: null,
    drive_file_url: null,
    sheets_sync_status: 'not_applicable',
    drive_sync_status: 'not_applicable',
    notes: null,
    source: 'manual',
    created_at: '2026-03-25T01:45:00Z',
    updated_at: '2026-03-25T01:45:00Z',
  },
  {
    id: 'demo-4',
    user_id: null,
    line_user_id: null,
    line_message_id: null,
    image_hash: null,
    status: 'confirmed',
    transaction_type: 'bill_payment',
    payment_status: 'success',
    amount: 850.00,
    currency: 'THB',
    date_display: '26 มี.ค. 2569',
    time_display: '14:22',
    transaction_datetime_iso: '2026-03-26T14:22:00+07:00',
    payer_name: 'นายแมน ธ***',
    receiver_name: null,
    merchant_name: 'การไฟฟ้านครหลวง',
    bank_name: 'Krungthai',
    reference_no: 'KTB202603261422001',
    merchant_code: null,
    transaction_code: null,
    fee: 0,
    category_guess: 'bills',
    category_final: 'bills',
    confidence_score: 0.95,
    raw_ocr_text: '',
    raw_provider_response: null,
    parsed_result: null,
    source_image_url: null,
    drive_file_url: null,
    sheets_sync_status: 'synced',
    drive_sync_status: 'synced',
    notes: 'ค่าไฟเดือน ก.พ.',
    source: 'line',
    created_at: '2026-03-26T07:22:00Z',
    updated_at: '2026-03-26T07:23:00Z',
  },
  {
    id: 'demo-5',
    user_id: null,
    line_user_id: null,
    line_message_id: null,
    image_hash: null,
    status: 'confirmed',
    transaction_type: 'qr_payment',
    payment_status: 'success',
    amount: 245.00,
    currency: 'THB',
    date_display: '27 มี.ค. 2569',
    time_display: '18:10',
    transaction_datetime_iso: '2026-03-27T18:10:00+07:00',
    payer_name: 'นายแมน ธ***',
    receiver_name: null,
    merchant_name: 'ร้านก๋วยเตี๋ยวเจ้าอร่อย',
    bank_name: 'KBank',
    reference_no: 'KBANK202603271810001',
    merchant_code: null,
    transaction_code: null,
    fee: 0,
    category_guess: 'food',
    category_final: 'food',
    confidence_score: 0.91,
    raw_ocr_text: '',
    raw_provider_response: null,
    parsed_result: null,
    source_image_url: null,
    drive_file_url: null,
    sheets_sync_status: 'pending',
    drive_sync_status: 'pending',
    notes: null,
    source: 'line',
    created_at: '2026-03-27T11:10:00Z',
    updated_at: '2026-03-27T11:11:00Z',
  },
  {
    id: 'demo-6',
    user_id: null,
    line_user_id: null,
    line_message_id: null,
    image_hash: null,
    status: 'ignored',
    transaction_type: 'other',
    payment_status: 'unknown',
    amount: 35.00,
    currency: 'THB',
    date_display: '27 มี.ค. 2569',
    time_display: '09:00',
    transaction_datetime_iso: '2026-03-27T09:00:00+07:00',
    payer_name: null,
    receiver_name: null,
    merchant_name: 'Unknown',
    bank_name: null,
    reference_no: null,
    merchant_code: null,
    transaction_code: null,
    fee: 0,
    category_guess: 'other',
    category_final: null,
    confidence_score: 0.32,
    raw_ocr_text: 'blurry text...',
    raw_provider_response: null,
    parsed_result: null,
    source_image_url: null,
    drive_file_url: null,
    sheets_sync_status: 'not_applicable',
    drive_sync_status: 'not_applicable',
    notes: 'ภาพเบลอ อ่านไม่ออก',
    source: 'line',
    created_at: '2026-03-27T02:00:00Z',
    updated_at: '2026-03-27T02:01:00Z',
  },
];
